---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/metalmatze/transmission-exporter

steps:
- name: build
  pull: default
  image: golang:1.13-alpine
  commands:
  - apk add -U git make
  - make fmt
  - make vet
  - make lint
  - make build

- name: docker-master
  pull: default
  image: plugins/docker
  settings:
    repo: metalmatze/transmission-exporter
    tags:
    - master
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-tag
  pull: default
  image: plugins/docker
  settings:
    repo: metalmatze/transmission-exporter
    tag:
    - 0.2
    - 0.2.1
    - latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - tag

...
